name: tzdata contents

on: [push]

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    env:
      TOXENV: py

    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.python-version }} - ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox
    - name: Run tests
      run: |
        tox

  other:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        toxenv: ["build", "pytype"]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.toxenv }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: Run action
        run: |
          tox
